name = "aiken/amm_dex_v2"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken/amm_dex_v2'"

[repository]
user = "aiken"
project = "amm_dex_v2"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
