name = "scisamir/always_success_mint"
version = "0.0.0"
compiler = "v1.1.9"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'scisamir/always_success_mint'"

[repository]
user = "scisamir"
project = "always_success_mint"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
